CREATE TABLE IF NOT EXISTS historical_analysis_job (
 reuniao_id UUID PRIMARY KEY,
 status VARCHAR(24) NOT NULL,
 resultado TEXT,
 criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
